# Cap. 5 — Produto interno e QR
*Ch. 5 — Inner product and QR*

Reproduz o slide «Álgebra Linear no computador» do deck **5 Produto interno e geometria (I)**. Para ver, não para exame.  
*Reproduces the slide “Linear algebra on the computer” (deck 5, I). Not examinable.*

In [1]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)   # saída mais legível / cleaner output

**Produto interno e norma** (5.1, 5.2). / *Inner product and norm.*

In [2]:
u = np.array([1, 2, -1])
v = np.array([3, 0, 2])
print('u . v =', u @ v)                          # 1
print('||(1,2,-2)|| =', np.linalg.norm([1, 2, -2]))  # 3

u . v = 1
||(1,2,-2)|| = 3.0


**Gram–Schmidt com matrizes: $A=QR$** (5.4). As colunas de $Q$ são a base ortonormada obtida à mão a partir de $(3,1)$ e $(2,2)$, a menos do sinal. / *Columns of Q: the orthonormal basis found by hand, up to sign.*

In [3]:
A = np.array([[3, 2],
              [1, 2]])          # colunas (3,1) e (2,2)
Q, R = np.linalg.qr(A)
print('Q =\n', Q)
print('R =\n', R)                  # triangular superior / upper triangular
print('Q^T Q =\n', Q.T @ Q)        # identidade / identity

Q =
 [[-0.9487 -0.3162]
 [-0.3162  0.9487]]
R =
 [[-3.1623 -2.5298]
 [ 0.      1.2649]]
Q^T Q =
 [[1. 0.]
 [0. 1.]]


In [4]:
print('à mão / by hand:', np.array([3, 1]) / np.sqrt(10), np.array([-1, 3]) / np.sqrt(10))

à mão / by hand: [0.9487 0.3162] [-0.3162  0.9487]


**Extensão: projeção sobre um subespaço** $V=L\{(1,1,0),(0,0,1)\}$. / *Extension: projection onto a subspace.*

In [5]:
e1 = np.array([1, 1, 0]) / np.sqrt(2)
e2 = np.array([0, 0, 1])
w = np.array([3, 1, 2])
p = (w @ e1) * e1 + (w @ e2) * e2
print('proj_V w =', p, '  resto / remainder:', w - p)   # (2,2,2), (1,-1,0)
print('resto . e1 =', (w - p) @ e1, '  resto . e2 =', (w - p) @ e2)

proj_V w = [2. 2. 2.]   resto / remainder: [ 1. -1.  0.]
resto . e1 = 6.470853991243019e-16   resto . e2 = 0.0


**Confere com os slides.** / *Matches the slides.*

In [ ]:
ok = (u @ v == 1 and np.isclose(np.linalg.norm([1, 2, -2]), 3)
      and np.allclose(Q.T @ Q, np.eye(2)) and np.allclose(Q @ R, A) and abs(R[1, 0]) < 1e-12
      and np.allclose(np.abs(Q[:, 0]), np.array([3, 1]) / np.sqrt(10))
      and np.allclose(p, [2, 2, 2]))
print("confere com os slides / matches the slides:", "sim / yes" if ok else "NÃO / NO")