# Cap. 6 — Valores próprios e longo prazo
*Ch. 6 — Eigenvalues and long-term behaviour*

Reproduz o slide «Álgebra Linear no computador» do deck **6 Valores e vetores próprios**. Para ver, não para exame.  
*Reproduces the slide “Linear algebra on the computer” (deck 6). Not examinable.*

In [1]:
import numpy as np
np.set_printoptions(precision=4, suppress=True)   # saída mais legível / cleaner output

**Exemplo 4**: à mão, $\lambda=2$ (vetores $(1,0,-2)$, $(0,1,0)$) e $\lambda=-1$ (vetor $(0,1,1)$). O computador devolve vetores **de norma 1**, por outra ordem: são os mesmos, a menos de um fator. / *Same eigenvectors up to a non-zero factor.*

In [2]:
C = np.array([[ 2, 0,  0],
              [-6, 2, -3],
              [-6, 0, -1]], dtype=float)
lam, P = np.linalg.eig(C)
print('valores próprios / eigenvalues:', lam)
print('P =\n', P)
print('P^-1 C P =\n', np.linalg.inv(P) @ C @ P)   # diagonal

valores próprios / eigenvalues: [ 2. -1.  2.]
P =
 [[ 0.      0.      0.4472]
 [ 1.      0.7071  0.    ]
 [ 0.      0.7071 -0.8944]]
P^-1 C P =
 [[ 2.  0.  0.]
 [ 0. -1.  0.]
 [ 0.  0.  2.]]


**Cidade e campo**: aplicar $M$ repetidamente leva $\mathbf x_k$ ao vetor próprio de $\lambda=1$, $(2/3,\,1/3)$ — o *método das potências*, ideia de base do PageRank. / *City and countryside: the power method.*

In [3]:
M = np.array([[0.9, 0.2],
              [0.1, 0.8]])
x = np.array([0.5, 0.5])
for k in range(1, 51):
    x = M @ x
    if k in (1, 10, 50):
        print(f'x_{k} =', x)

x_1 = [0.55 0.45]
x_10 = [0.662 0.338]
x_50 = [0.6667 0.3333]


Experimente outro ponto de partida, por exemplo $(1, 0)$: o limite é o mesmo. / *Try another starting point: same limit.*

In [4]:
x = np.array([1.0, 0.0])
for k in range(50):
    x = M @ x
x

array([0.6667, 0.3333])